meta:
  symbol: tBTCUSD
  timeframe: 1h
  snapshot_id: tBTCUSD_1h_2024-10-22_2025-10-01_v1
  warmup_bars: 150
  runs:
    strategy: grid
    max_trials: 2
    max_concurrent: 1
    resume: false
  use_sample_range: true
  sample_start: 2024-10-22
  sample_end: 2025-10-01

parameters:
  thresholds:
    entry_conf_overall:
      type: fixed
      value: 0.45
    regime_proba:
      balanced:
        type: fixed
        value: 0.5
      ranging:
        type: fixed
        value: 0.35
      bull:
        type: fixed
        value: 0.58
      bear:
        type: fixed
        value: 0.58

  risk:
    risk_map:
      type: fixed
      value: [[0.45, 0.02], [0.55, 0.035], [0.65, 0.05]]

  gates:
    hysteresis_steps:
      type: fixed
      value: 2
    cooldown_bars:
      type: fixed
      value: 0

  exit:
    exit_conf_threshold:
      type: fixed
      value: 0.42
    max_hold_bars:
      type: fixed
      value: 18
    regime_aware_exits:
      type: fixed
      value: true

  htf_exit_config:
    fib_threshold_atr:
      type: grid
      values: [0.6]
    trail_atr_multiplier:
      type: grid
      values: [1.9, 2.1]
    enable_partials:
      type: fixed
      value: true
    enable_trailing:
      type: fixed
      value: true
    enable_structure_breaks:
      type: fixed
      value: true
    partial_1_pct:
      type: fixed
      value: 0.4
    partial_2_pct:
      type: fixed
      value: 0.3
    swing_update_strategy:
      type: fixed
      value: fixed

  htf_fib:
    entry:
      enabled:
        type: fixed
        value: true
      missing_policy:
        type: fixed
        value: pass
      tolerance_atr:
        type: grid
        values: [0.3]
      long_target_levels:
        type: fixed
        value: [0.5, 0.618, 0.786]
      short_target_levels:
        type: fixed
        value: [0.382, 0.5, 0.618]
      long_min_level:
        type: fixed
        value: 0.382
      short_max_level:
        type: fixed
        value: 0.618

  ltf_fib:
    entry:
      enabled:
        type: fixed
        value: true
      missing_policy:
        type: fixed
        value: pass
      tolerance_atr:
        type: grid
        values: [0.3]
      long_max_level:
        type: fixed
        value: 0.786
      short_min_level:
        type: fixed
        value: 0.382

