meta:
  symbol: tBTCUSD
  timeframe: 1h
  snapshot_id: tBTCUSD_1h_2024-10-22_2025-10-01_v1
  warmup_bars: 150
  runs:
    strategy: optuna
    max_trials: 2
    max_concurrent: 1
    resume: true
    optuna:
      storage: sqlite:///optuna_tBTCUSD_1h_fib_tune_resume.db
      study_name: tBTCUSD_1h_fib_tune_resume
      sampler:
        name: tpe
        kwargs: {}
      pruner:
        name: median
        kwargs: {}
      heartbeat_interval: 30
      heartbeat_grace_period: 90
      timeout_seconds: 300
  use_sample_range: true
  sample_start: 2024-10-22
  sample_end: 2025-10-01

parameters:
  thresholds:
    entry_conf_overall:
      type: float
      low: 0.4
      high: 0.45
      step: 0.05
    signal_adaptation:
      type: fixed
      value:
        atr_period: 14
        zones:
          low:
            entry_conf_overall: 0.36
            regime_proba:
              ranging: 0.7
              bull: 0.6
              bear: 0.6
              balanced: 0.7
          mid:
            entry_conf_overall: 0.42
            regime_proba:
              ranging: 0.8
              bull: 0.7
              bear: 0.7
              balanced: 0.8
          high:
            entry_conf_overall: 0.48
            regime_proba:
              ranging: 0.88
              bull: 0.78
              bear: 0.78
              balanced: 0.88
  risk:
    risk_map:
      type: grid
      values:
        - [[0.45, 0.015], [0.55, 0.025], [0.65, 0.035]]
  exit:
    exit_conf_threshold:
      type: float
      low: 0.4
      high: 0.45
      step: 0.05
    max_hold_bars:
      type: grid
      values: [18]
  htf_exit_config:
    fib_threshold_atr:
      type: float
      low: 0.6
      high: 0.65
      step: 0.05
    trail_atr_multiplier:
      type: float
      low: 1.9
      high: 2.2
      step: 0.3
    enable_partials:
      type: fixed
      value: true
    enable_trailing:
      type: fixed
      value: true
    enable_structure_breaks:
      type: fixed
      value: true
    partial_1_pct:
      type: fixed
      value: 0.6
    partial_2_pct:
      type: fixed
      value: 0.5
    swing_update_strategy:
      type: fixed
      value: fixed
  htf_fib:
    entry:
      enabled:
        type: fixed
        value: true
      missing_policy:
        type: fixed
        value: pass
      tolerance_atr:
        type: float
        low: 0.3
        high: 0.35
        step: 0.05
      long_min_level:
        type: fixed
        value: 0.382
      short_max_level:
        type: fixed
        value: 0.618
  ltf_fib:
    entry:
      enabled:
        type: fixed
        value: true
      missing_policy:
        type: fixed
        value: pass
      tolerance_atr:
        type: float
        low: 0.3
        high: 0.35
        step: 0.05
      long_max_level:
        type: fixed
        value: 0.786
      short_min_level:
        type: fixed
        value: 0.382
