meta:
  symbol: tBTCUSD
  timeframe: 1h
  snapshot_id: tBTCUSD_1h_2024-10-22_2025-10-01_v1
  warmup_bars: 50
  runs:
    max_trials: 15
    strategy: optuna
    max_concurrent: 2
    resume: true
    optuna:
      storage: sqlite:///optuna_tBTCUSD_1h_fib.db
      study_name: tBTCUSD_1h_fib
      sampler:
        name: tpe
        kwargs: {}
      pruner:
        name: hyperband
        kwargs:
          min_resource: 250
          reduction_factor: 3
      timeout_seconds: 900
  use_sample_range: true
  sample_start: 2025-04-01
  sample_end: 2025-10-01

parameters:
  thresholds:
    entry_conf_overall:
      type: fixed
      value: 0.35
    regime_proba:
      balanced:
        type: fixed
        value: 0.7
  risk:
    risk_map:
      type: fixed
      value: [[0.45, 0.015], [0.55, 0.025], [0.65, 0.035]]
  exit:
    exit_conf_threshold:
      type: fixed
      value: 0.4
    max_hold_bars:
      type: fixed
      value: 20
  htf_exit_config:
    fib_threshold_atr:
      type: float
      low: 0.5
      high: 0.9
      step: 0.02
    trail_atr_multiplier:
      type: float
      low: 2.0
      high: 3.0
      step: 0.1
    partial_1_pct:
      type: float
      low: 0.5
      high: 0.7
      step: 0.02
    partial_2_pct:
      type: float
      low: 0.4
      high: 0.6
      step: 0.02
