meta:
  symbol: tBTCUSD
  timeframe: 1h
  snapshot_id: tBTCUSD_1h_2024-10-22_2025-10-01_v1
  warmup_bars: 50
  runs:
    strategy: grid
    max_trials: 16
    max_concurrent: 1
    resume: false
  use_sample_range: true
  sample_start: 2025-04-01
  sample_end: 2025-10-01

parameters:
  thresholds:
    entry_conf_overall:
      type: fixed
      value: 0.35
    regime_proba:
      balanced:
        type: fixed
        value: 0.7
  risk:
    risk_map:
      type: fixed
      value: [[0.45, 0.015], [0.55, 0.025], [0.65, 0.035]]
  exit:
    exit_conf_threshold:
      type: fixed
      value: 0.4
    max_hold_bars:
      type: fixed
      value: 20
  htf_exit_config:
    fib_threshold_atr:
      type: grid
      values: [0.6, 0.75]
    trail_atr_multiplier:
      type: grid
      values: [2.4, 2.8]
    enable_partials:
      type: grid
      values: [true, false]
    enable_trailing:
      type: grid
      values: [true, false]
    partial_1_pct:
      type: fixed
      value: 0.6
    partial_2_pct:
      type: fixed
      value: 0.5
    enable_structure_breaks:
      type: fixed
      value: true
    swing_update_strategy:
      type: fixed
      value: fixed
