meta:
  symbol: tBTCUSD
  timeframe: 1h
  snapshot_id: tBTCUSD_1h_2024-10-22_2025-10-01_v1
  baseline_config: config/timeframe_configs.py:get_1h_config
  warmup_bars: 150
  runs:
    max_trials: 3
    strategy: grid
    max_concurrent: 1
    resume: true
    use_sample_range: true
    sample_start: 2025-04-01
    sample_end: 2025-06-30
parameters:
  thresholds:
    entry_conf_overall:
      type: grid
      values: [0.5, 0.6, 0.7]
    regime_proba:
      balanced:
        type: grid
        values: [0.55, 0.6, 0.65]
  risk:
    risk_map:
      type: grid
      values:
        - [[0.6, 0.02], [0.7, 0.03], [0.8, 0.04], [0.9, 0.05]]
        - [[0.5, 0.015], [0.6, 0.025], [0.7, 0.035], [0.8, 0.045], [0.9, 0.055]]
  exit:
    exit_conf_threshold:
      type: grid
      values: [0.4, 0.45, 0.5]
    max_hold_bars:
      type: grid
      values: [15, 20, 25]
