meta:
  symbol: tBTCUSD
  timeframe: 1h
  snapshot_id: tBTCUSD_1h_2024-10-22_2025-10-01_v1
  baseline_config: config/timeframe_configs.py:get_1h_config
  warmup_bars: 150
  runs:
    max_trials: 2
    strategy: grid
    max_concurrent: 1
    resume: true
parameters:
  thresholds:
    entry_conf_overall:
      type: grid
      values: [0.38, 0.40, 0.42]
    regime_proba:
      ranging:
        type: grid
        values: [0.78, 0.82]
      bull:
        type: fixed
        value: 0.70
      bear:
        type: fixed
        value: 0.70
      balanced:
        type: fixed
        value: 0.80
    signal_adaptation:
      enabled:
        type: fixed
        value: true
      atr_period:
        type: fixed
        value: 14
      zones:
        low:
          entry_conf_overall:
            type: grid
            values: [0.36, 0.38]
          regime_proba:
            ranging:
              type: grid
              values: [0.70, 0.74]
            bull:
              type: fixed
              value: 0.64
            bear:
              type: fixed
              value: 0.64
            balanced:
              type: fixed
              value: 0.72
        mid:
          entry_conf_overall:
            type: fixed
            value: 0.44
          regime_proba:
            ranging:
              type: fixed
              value: 0.84
            bull:
              type: fixed
              value: 0.74
            bear:
              type: fixed
              value: 0.74
            balanced:
              type: fixed
              value: 0.84
        high:
          entry_conf_overall:
            type: fixed
            value: 0.48
          regime_proba:
            ranging:
              type: fixed
              value: 0.90
            bull:
              type: fixed
              value: 0.80
            bear:
              type: fixed
              value: 0.80
            balanced:
              type: fixed
              value: 0.90
  risk:
    risk_map:
      type: grid
      values:
        - [[0.50, 0.03], [0.60, 0.05], [0.70, 0.08], [0.80, 0.11], [0.90, 0.14]]
        - [[0.48, 0.025], [0.58, 0.045], [0.68, 0.07], [0.78, 0.095], [0.88, 0.12]]
    exit:
      exit_conf_threshold:
        type: grid
        values: [0.46, 0.48]
      max_hold_bars:
        type: fixed
        value: 24
      partial_1_pct:
        type: grid
        values: [0.45, 0.55]
      partial_2_pct:
        type: fixed
        value: 0.35
      fib_threshold_atr:
        type: fixed
        value: 0.60
      trail_atr_multiplier:
        type: fixed
        value: 2.1
constraints:
  min_trades: 60
  min_profit_factor: 1.35
  max_max_dd: 0.12
  prior_config_penalty:
    baseline: config/timeframe_configs.py:get_1h_config
    penalty_factor: 0.02
  zone_consistency:
    enforce: true
    allowed_diff: 0.10
