meta:
  symbol: tBTCUSD
  timeframe: 1h
  snapshot_id: tBTCUSD_1h_2024-10-22_2025-10-01_v1
  baseline_config: config/timeframe_configs.py:get_1h_config
  warmup_bars: 150
  runs:
    max_trials: 120
    strategy: grid
parameters:
  thresholds:
    entry_conf_overall:
      type: grid
      values: [0.36, 0.38, 0.40, 0.42, 0.44]
    regime_proba:
      ranging:
        type: grid
        values: [0.75, 0.80, 0.85]
      bull:
        type: grid
        values: [0.65, 0.70, 0.75]
      bear:
        type: grid
        values: [0.65, 0.70, 0.75]
      balanced:
        type: grid
        values: [0.75, 0.80, 0.85]
    signal_adaptation:
      enabled:
        type: fixed
        value: true
      atr_period:
        type: grid
        values: [14, 21]
      zones:
        low:
          entry_conf_overall:
            type: grid
            values: [0.36, 0.38, 0.40]
          regime_proba:
            ranging:
              type: grid
              values: [0.70, 0.75]
            bull:
              type: grid
              values: [0.60, 0.65]
            bear:
              type: grid
              values: [0.60, 0.65]
            balanced:
              type: grid
              values: [0.70, 0.75]
        mid:
          entry_conf_overall:
            type: grid
            values: [0.42, 0.44]
          regime_proba:
            ranging:
              type: grid
              values: [0.80, 0.85]
            bull:
              type: grid
              values: [0.70, 0.75]
            bear:
              type: grid
              values: [0.70, 0.75]
            balanced:
              type: grid
              values: [0.80, 0.85]
        high:
          entry_conf_overall:
            type: grid
            values: [0.46, 0.50]
          regime_proba:
            ranging:
              type: grid
              values: [0.85, 0.90]
            bull:
              type: grid
              values: [0.75, 0.80]
            bear:
              type: grid
              values: [0.75, 0.80]
            balanced:
              type: grid
              values: [0.85, 0.90]
  risk:
    risk_map:
      type: grid
      values:
        - [[0.50, 0.03], [0.60, 0.05], [0.70, 0.08], [0.80, 0.10], [0.90, 0.12]]
        - [[0.48, 0.02], [0.58, 0.04], [0.68, 0.07], [0.78, 0.09], [0.88, 0.11]]
        - [[0.52, 0.04], [0.62, 0.06], [0.72, 0.09], [0.82, 0.12], [0.92, 0.14]]
    exit:
      exit_conf_threshold:
        type: grid
        values: [0.45, 0.48, 0.50]
      max_hold_bars:
        type: grid
        values: [20, 25, 30]
      partial_1_pct:
        type: grid
        values: [0.40, 0.50, 0.60]
      partial_2_pct:
        type: grid
        values: [0.30, 0.40, 0.50]
      fib_threshold_atr:
        type: grid
        values: [0.5, 0.6, 0.7]
      trail_atr_multiplier:
        type: grid
        values: [1.8, 2.0, 2.2, 2.5]
constraints:
  min_trades: 30
  min_profit_factor: 1.2
  max_max_dd: 0.15
  prior_config_penalty:
    baseline: config/timeframe_configs.py:get_1h_config
    penalty_factor: 0.02
  zone_consistency:
    enforce: true
    allowed_diff: 0.12
