meta:
  symbol: tBTCUSD
  timeframe: 1h
  snapshot_id: tBTCUSD_1h_2024-10-22_2025-10-01_v1
  warmup_bars: 50
  runs:
    max_trials: 12
    strategy: optuna
    max_concurrent: 2
    resume: true
    optuna:
      storage: sqlite:///optuna_tBTCUSD_1h_micro.db
      study_name: tBTCUSD_1h_micro
      sampler:
        name: tpe
        kwargs: {}
      pruner:
        name: hyperband
        kwargs:
          min_resource: 250
          reduction_factor: 3
      timeout_seconds: 900
  use_sample_range: true
  sample_start: 2025-04-01
  sample_end: 2025-10-01

parameters:
  thresholds:
    entry_conf_overall:
      type: float
      low: 0.33
      high: 0.38
      step: 0.01
    regime_proba:
      balanced:
        type: float
        low: 0.65
        high: 0.75
        step: 0.01
  risk:
    risk_map:
      type: grid
      values:
        - [[0.44, 0.013], [0.54, 0.023], [0.64, 0.033]]
        - [[0.45, 0.015], [0.55, 0.025], [0.65, 0.035]]
        - [[0.46, 0.017], [0.56, 0.027], [0.66, 0.037]]
  exit:
    exit_conf_threshold:
      type: float
      low: 0.35
      high: 0.45
      step: 0.01
    max_hold_bars:
      type: grid
      values: [18, 20]
  htf_exit_config:
    fib_threshold_atr:
      type: float
      low: 0.6
      high: 0.8
      step: 0.02
    trail_atr_multiplier:
      type: float
      low: 2.2
      high: 2.8
      step: 0.1
